services:
  docling:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_CUDA: ${DOCLING_ENABLE_CUDA:-false}
    environment:
      - DOCLING_GPU_PREFERRED=${DOCLING_GPU_PREFERRED:-true}
      - DOCLING_STORAGE_PATH=/data
    ports:
      - "5001:5001"
    volumes:
      - ./storage/docling:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    restart: unless-stopped
    restart: "no"
